name: flight_analytics
version: '1.0'
config-version: 2

profile: flight_analytics

source-paths: ["models"]
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

models:
  flight_analytics:
    +materialized: view
    staging:
      +materialized: view
    marts:
      +materialized: table
